runtime: python27
api_version: 1
threadsafe: yes
vm: true

handlers:
  - url: /favicon\.png
    static_files: favicon.png
    upload: favicon\.png

  - url: /robots\.txt
    static_files: robots.txt
    upload: robots\.txt

  - url: /images
    static_dir: images

  - url: /bundles
    static_dir: bundles

  - url: /.*
    # secure: always
    static_files: index.html
    upload: index.html
