
###
# Development environment configuration
##

# Application settings
APP_NAME: '${pkg.name}'
APP_VERSION: '${pkg.version}'
APP_TITLE: 'My Application'
APP_BASE_URL: 'http://localhost:8080'

# API settings
API_VERSION: 1
API_BASE_URL: 'http://localhost:8081/api/v1'

# Authentication settings
AUTH_CLIENT_IDENTIFIER: '${pkg.name}'
