
###
# Development environment configuration
##

# Application settings
APP_NAME: '${pkg.name}'
APP_VERSION: '${pkg.version}'
APP_TITLE: 'My Application [dev]'
APP_BASE_URL: 'http://localhost:8080'

# API settings
API_VERSION: 1
API_BASE_URL: 'http://localhost:8081/api/v1'
API_ENFORCE_DATA_FORMAT: true
API_VERBOSE: true

# Authentication settings
AUTH_CLIENT_IDENTIFIER: '${pkg.name}'

# Analytics settings
ANALYTICS_ENABLED: false
ANALYTICS_TRACKING_ID: ''
